# Generated by Django 4.1 on 2022-08-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_CreacionTablaAdministrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField(default='https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')),
                ('adminId', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='administrador.usuario')),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
    ]
